const restaurants = [
  {
    name: "南蛮子（进贤路店）",
    name_en: "Nán Mán Zǐ (Jinxian Rd)",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "法租界 · 浦西核心区",
    neighborhood_en: "French Concession · Puxi",
    address: "进贤路，徐汇区",
    address_en: "Jinxian Rd, Xuhui District",
    description: "云南菜馆，藏在法租界的街边小店。环境简朴，明厨亮灶，隔着玻璃能直接看见后厨操作。烟火气十足，更适合朋友聚餐而非正式请客。没有包间，但有大圆桌，2到10个人都能坐得舒服。",
    description_en: "A no-frills Yunnan restaurant tucked into a side street in the French Concession. Lively and unpretentious — perfect for a casual dinner with friends. No private rooms, but the large round tables fit groups of 2 to 10 easily.",
    mustTry: ["黑三剁", "木姜子牛肉", "菌子鸡汤", "炸排骨", "烤罗非鱼", "酥红豆", "辣子鸡", "牙签牛肉"],
    mustTry_en: ["Black Three-Mince (黑三剁)", "Litsea Beef (木姜子牛肉)", "Wild Mushroom Chicken Soup (菌子鸡汤)", "Fried Pork Ribs (炸排骨)", "Grilled Tilapia (烤罗非鱼)", "Crispy Red Beans (酥红豆)", "Chilli Chicken (辣子鸡)", "Toothpick Beef (牙签牛肉)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥100",
    perPerson_en: "~¥100 / person",
    reservation: "平时无需预定，周末饭点可在大众点评提前订位",
    reservation_en: "Walk-ins welcome on weekdays. For weekend peak hours, book ahead on Dianping.",
    groupSize: "2–10 人",
    groupSize_en: "2–10 people",
    occasion: "朋友聚餐",
    occasion_en: "Friends dinner",
    atmosphere: "简朴",
    atmosphere_en: "Casual",
    emoji: "🌿",
    rating: "夯",
    spicy: 1,
    dianping: "https://m.dianping.com/shop/2201962"
  },
  {
    name: "野果与山椒",
    name_en: "Yěguǒ & Shānjiāo",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "静安区 · 浦西",
    neighborhood_en: "Jing'an · Puxi",
    address: "两家分店：富民路店 / 长寿路店（均在静安区）",
    address_en: "Two locations: Fumin Rd / Changshou Rd (both Jing'an District)",
    description: "火龙果心中上海第二名！贵州菜，非常正宗，烟火气与精致感并存。人少时直接点菜，比酸汤火锅更好吃。这里的鸡尾酒调得出奇地好，值得专程一试。",
    description_en: "火龙果's #2 in Shanghai! Authentic Guizhou cuisine — honest, flavourful, and surprisingly refined. Skip the sour-broth hotpot if you're a small group and order à la carte instead — the dishes are the real star. The cocktails here are also excellent.",
    mustTry: ["宫爆板筋", "铁签烤肉", "牛肉青菜锅", "辣子鸡", "脆哨土豆", "水豆豉茼蒿", "豆腐圆子", "洋芋粑"],
    mustTry_en: ["Kung Pao Tendon (宫爆板筋)", "Skewer Grilled Meat (铁签烤肉)", "Beef & Greens Pot (牛肉青菜锅)", "Chilli Chicken (辣子鸡)", "Crispy Lard Potato (脆哨土豆)", "Fermented Soybean Chrysanthemum (水豆豉茼蒿)", "Tofu Balls (豆腐圆子)", "Potato Cake (洋芋粑)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥120",
    perPerson_en: "~¥120 / person",
    reservation: "强烈建议提前在大众点评订位",
    reservation_en: "Reservations strongly recommended — book ahead on Dianping.",
    groupSize: "2–8 人",
    groupSize_en: "2–8 people",
    occasion: "朋友聚餐 / 回国必吃",
    occasion_en: "Friends dinner / Must-eat on return",
    atmosphere: "热闹",
    atmosphere_en: "Lively",
    rating: "夯",
    spicy: 3,
    dianping: "https://m.dianping.com/shop/731796035",
    dianping2: "https://m.dianping.com/shop/1846224196",
    dianping2_label: "大众点评（长寿路店）",
    dianping2_label_en: "Dianping (Changshou Rd)",
  },
  {
    name: "卿家姆",
    name_en: "Qīng Jiā Mǔ",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市各区均有门店，外滩店位置尤佳",
    address_en: "Locations across all districts; the Bund branch has the best location",
    description: "从宁波开来上海的江浙小海鲜馆子，精致而不做作。外滩店位置很好，但大厅无法订位，周末可能需要等位；包间可订但低消离谱，不建议。适合朋友聚餐或小规模请客，不适合家庭大桌。",
    description_en: "A Ningbo-origin Jiangzhe seafood restaurant, refined without being stuffy. The Bund branch has a great location — no reservations for the main hall (expect a wait on weekends), and private rooms have an unreasonable minimum spend. Best for friends or intimate hosting, not large family gatherings.",
    mustTry: ["熟醉大头虾", "小馆红烧肉", "爆炒黄牛肉", "腐竹黄鱼卷", "熟醉大闸蟹", "葱油东海小馆"],
    mustTry_en: ["Drunken Prawns (熟醉大头虾)", "Braised Pork — not sweet! (小馆红烧肉)", "Stir-fried Yellow Beef (爆炒黄牛肉)", "Tofu Skin & Yellow Croaker Roll (腐竹黄鱼卷)", "Drunken Hairy Crab (熟醉大闸蟹)", "Scallion Oil East Sea Catch (葱油东海小馆)"],
    priceRange: "¥¥¥",
    perPerson: "人均 ¥150–200",
    perPerson_en: "~¥150–200 / person",
    reservation: "大厅不可订位；包间可订但低消极高，不建议",
    reservation_en: "No reservations for main hall; private rooms available but minimum spend is excessive — not recommended.",
    groupSize: "2–4 人",
    groupSize_en: "2–4 people",
    occasion: "朋友聚餐 / 小规模请客",
    occasion_en: "Friends dinner / Intimate hosting",
    atmosphere: "精致",
    atmosphere_en: "Refined",
    rating: "夯",
    dianping: "https://m.dianping.com/shop/1022572955"
  },
];
