const restaurants = [
  {
    name: "南蛮子（进贤路店）",
    name_en: "Nán Mán Zǐ (Jinxian Rd)",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "法租界 · 浦西核心区",
    neighborhood_en: "French Concession · Puxi",
    address: "进贤路，徐汇区",
    address_en: "Jinxian Rd, Xuhui District",
    description: "云南菜馆，藏在法租界的街边小店。环境简朴，明厨亮灶，隔着玻璃能直接看见后厨操作。烟火气十足，更适合朋友聚餐而非正式请客。没有包间，但有大圆桌，2到10个人都能坐得舒服。",
    description_en: "A no-frills Yunnan restaurant tucked into a side street in the French Concession. Lively and unpretentious — perfect for a casual dinner with friends. No private rooms, but the large round tables fit groups of 2 to 10 easily.",
    mustTry: ["黑三剁", "木姜子牛肉", "菌子鸡汤", "炸排骨", "烤罗非鱼", "酥红豆", "辣子鸡", "牙签牛肉"],
    mustTry_en: ["Black Three-Mince (黑三剁)", "Litsea Beef (木姜子牛肉)", "Wild Mushroom Chicken Soup (菌子鸡汤)", "Fried Pork Ribs (炸排骨)", "Grilled Tilapia (烤罗非鱼)", "Crispy Red Beans (酥红豆)", "Chilli Chicken (辣子鸡)", "Toothpick Beef (牙签牛肉)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥100",
    perPerson_en: "~¥100 / person",
    reservation: "平时无需预定，周末饭点可在大众点评提前订位",
    reservation_en: "Walk-ins welcome on weekdays. For weekend peak hours, book ahead on Dianping.",
    groupSize: "2–10 人",
    groupSize_en: "2–10 people",
    occasion: "朋友聚餐",
    occasion_en: "Friends dinner",
    atmosphere: "简朴",
    atmosphere_en: "Casual",
    emoji: "🌿",
    rating: 3,
    spicy: 1,
    dianping: "https://m.dianping.com/shop/2201962"
  },
  {
    name: "野果与山椒",
    name_en: "Yěguǒ & Shānjiāo",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "静安区 · 浦西",
    neighborhood_en: "Jing'an · Puxi",
    address: "两家分店：富民路店 / 长寿路店（均在静安区）",
    address_en: "Two locations: Fumin Rd / Changshou Rd (both Jing'an District)",
    description: "火龙果心中上海第二名！贵州菜，非常正宗，烟火气与精致感并存。人少时直接点菜，比酸汤火锅更好吃。这里的鸡尾酒调得出奇地好，值得专程一试。",
    description_en: "火龙果's #2 in Shanghai! Authentic Guizhou cuisine — honest, flavourful, and surprisingly refined. Skip the sour-broth hotpot if you're a small group and order à la carte instead — the dishes are the real star. The cocktails here are also excellent.",
    mustTry: ["宫爆板筋", "铁签烤肉", "牛肉青菜锅", "辣子鸡", "脆哨土豆", "水豆豉茼蒿", "豆腐圆子", "洋芋粑"],
    mustTry_en: ["Kung Pao Tendon (宫爆板筋)", "Skewer Grilled Meat (铁签烤肉)", "Beef & Greens Pot (牛肉青菜锅)", "Chilli Chicken (辣子鸡)", "Crispy Lard Potato (脆哨土豆)", "Fermented Soybean Chrysanthemum (水豆豉茼蒿)", "Tofu Balls (豆腐圆子)", "Potato Cake (洋芋粑)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥120",
    perPerson_en: "~¥120 / person",
    reservation: "强烈建议提前在大众点评订位",
    reservation_en: "Reservations strongly recommended — book ahead on Dianping.",
    groupSize: "2–8 人",
    groupSize_en: "2–8 people",
    occasion: "朋友聚餐 / 回国必吃",
    occasion_en: "Friends dinner / Must-eat on return",
    atmosphere: "热闹",
    atmosphere_en: "Lively",
    rating: 2,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/731796035", label: "大众点评（富民路店）", label_en: "Dianping (Fumin Rd)" },
      { url: "https://m.dianping.com/shop/1846224196", label: "大众点评（长寿路店）", label_en: "Dianping (Changshou Rd)" },
    ],
  },
  {
    name: "卿家姆",
    name_en: "Qīng Jiā Mǔ",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市各区均有门店，外滩店位置尤佳",
    address_en: "Locations across all districts; the Bund branch has the best location",
    description: "从宁波开来上海的江浙小海鲜馆子，精致而不做作。外滩店位置很好，但大厅无法订位，周末可能需要等位；包间可订但低消离谱，不建议。适合朋友聚餐或小规模请客，不适合家庭大桌。",
    description_en: "A Ningbo-origin Jiangzhe seafood restaurant, refined without being stuffy. The Bund branch has a great location — no reservations for the main hall (expect a wait on weekends), and private rooms have an unreasonable minimum spend. Best for friends or intimate hosting, not large family gatherings.",
    mustTry: ["熟醉大头虾", "小馆红烧肉", "爆炒黄牛肉", "腐竹黄鱼卷", "熟醉大闸蟹", "葱油东海小馆"],
    mustTry_en: ["Drunken Prawns (熟醉大头虾)", "Braised Pork — not sweet! (小馆红烧肉)", "Stir-fried Yellow Beef (爆炒黄牛肉)", "Tofu Skin & Yellow Croaker Roll (腐竹黄鱼卷)", "Drunken Hairy Crab (熟醉大闸蟹)", "Scallion Oil East Sea Catch (葱油东海小馆)"],
    priceRange: "¥¥¥",
    perPerson: "人均 ¥150–200",
    perPerson_en: "~¥150–200 / person",
    reservation: "大厅不可订位；包间可订但低消极高，不建议",
    reservation_en: "No reservations for main hall; private rooms available but minimum spend is excessive — not recommended.",
    groupSize: "2–4 人",
    groupSize_en: "2–4 people",
    occasion: "朋友聚餐 / 小规模请客",
    occasion_en: "Friends dinner / Intimate hosting",
    atmosphere: "精致",
    atmosphere_en: "Refined",
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/1022572955", label: "大众点评（外滩店）", label_en: "Dianping (Bund)" },
      { url: "https://m.dianping.com/shop/877017586", label: "大众点评（中山公园店）", label_en: "Dianping (Zhongshan Park)" },
    ],
  },
  {
    name: "山石榴",
    name_en: "Shān Shí Liú",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市各区均有门店",
    address_en: "Locations across all districts",
    description: "贵州菜，正宗正常，性价比高。连锁店到处都有，想吃贵州菜随时可以去。",
    description_en: "Authentic, no-fuss Guizhou cuisine with solid value. Locations all over the city — reliable whenever a Guizhou craving hits.",
    mustTry: ["铁签烤肉", "辣子鸡"],
    mustTry_en: ["Skewer Grilled Meat (铁签烤肉)", "Chilli Chicken (辣子鸡)"],
    priceRange: "¥¥",
    occasion: "随性聚餐",
    occasion_en: "Casual dining",
    atmosphere: "热闹",
    atmosphere_en: "Lively",
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    rating: 1,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/113900524", label: "大众点评（南京西路丰盛里店）", label_en: "Dianping (Fengsheng Li, W Nanjing Rd)" },
      { url: "https://m.dianping.com/shop/1985625539", label: "大众点评（淮海路店）", label_en: "Dianping (Huaihai Rd)" },
    ],
  },
  {
    name: "清晨落夜小酒馆",
    name_en: "Qīngchén Luòyè Xiǎojiǔguǎn",
    category: "jiangxi",
    category_en: "jiangxi",
    neighborhood: "静安寺 · 静安区",
    neighborhood_en: "Jing'an Temple · Jing'an District",
    address: "静安寺附近，静安区",
    address_en: "Near Jing'an Temple, Jing'an District",
    description: "江西菜小酒馆，江西人认证正宗。辣得很，爆炒的菜都挺好吃。",
    description_en: "Jiangxi cuisine wine bar, certified authentic by actual Jiangxi locals. Seriously spicy — the stir-fried dishes are the highlights.",
    mustTry: ["爆炒系列菜"],
    mustTry_en: ["Stir-fried dishes (爆炒系列)"],
    occasion: "朋友聚餐",
    occasion_en: "Friends dinner",
    atmosphere: "小酒馆",
    atmosphere_en: "Wine bar vibes",
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    rating: 2,
    spicy: 5,
    dianping: "https://m.dianping.com/shop/1804042946",
  },
  {
    name: "炙苑",
    name_en: "Zhì Yuàn",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "浦东 · 世纪公园板块",
    neighborhood_en: "Pudong · Century Park",
    address: "浦东嘉里城，浦东新区",
    address_en: "Kerry Parkside, Pudong New Area",
    description: "日式烧肉天花板，没有并列的。什么肉都好吃，可以根据人数和喜好点拼盘，反正点下来都差不多贵。碾压铁屋、老干杯、橘炎胡同等一众高端日式烧肉。人均500不含酒已经能吃得非常满足。",
    description_en: "The undisputed peak of Japanese yakiniku in Shanghai — nothing comes close. Every cut is exceptional; order a combo platter sized to your group. Leaves Iron House, Don Quijote, and every other high-end yakiniku in the dust. ¥500/person ex-drinks is more than satisfying.",
    mustTry: ["拼盘（按人数点）", "和牛海胆塔塔", "海胆和牛釜饭"],
    mustTry_en: ["Combo Platter (sized to group)", "Wagyu & Uni Tartare (和牛海胆塔塔)", "Uni Wagyu Kamameshi (海胆和牛釜饭)"],
    priceRange: "¥¥¥¥",
    perPerson: "人均 ¥500（不点酒）",
    perPerson_en: "~¥500 / person (ex-drinks)",
    reservation: "可提前订位，有包间",
    reservation_en: "Reservations available; private rooms offered.",
    groupSize: "2–6 人",
    groupSize_en: "2–6 people",
    occasion: "朋友聚餐 / 请客",
    occasion_en: "Friends dinner / Hosting",
    atmosphere: "高端精致",
    atmosphere_en: "Upscale",
    rating: 3,
    dianping: "https://www.dianping.com/shop/H3pRXBQ0J4tT09I2",
  },
  {
    name: "鮨小野",
    name_en: "Sushi Ono",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "世纪公园 / 前滩（两家均可）",
    neighborhood_en: "Century Park / Qiantan (both branches)",
    address: "两家分店：世纪公园店 / 前滩店",
    address_en: "Two branches: Century Park / Qiantan",
    description: "板前寿司，可以自己点单——千万不要点套餐，直接点你想吃的，每一样都极度新鲜！火龙果力推：比很多人均1k+的日料还新鲜还好吃，性价比和味道全部拉满。因为只有板前，人多了坐一排会根本听不到彼此说话，2-3人最适合。必须提前大众点评预约，座位有限！",
    description_en: "Omakase-counter sushi where you order à la carte — skip the set menu and just pick what you want, everything is supremely fresh! 火龙果's top pick: beats many ¥1000+/head places on both quality and value. Counter-only seating means groups of 4+ can't really talk to each other — keep it to 2–3. Dianping reservation required, seats are limited!",
    mustTry: ["各类海胆", "枪鱿鱼", "金枪鱼", "枪鱿鱼海胆寿司（火龙果挚爱）"],
    mustTry_en: ["Sea Urchin (all kinds)", "Squid (枪鱿鱼)", "Tuna (金枪鱼)", "Squid & Uni Sushi — 火龙果's #1 pick"],
    perPerson: "人均 ¥500–800（不含酒）",
    perPerson_en: "~¥500–800 / person (excl. drinks)",
    reservation: "必须提前大众点评预约，座位非常有限",
    reservation_en: "Dianping reservation required — very limited seats",
    groupSize: "2–3 人",
    groupSize_en: "2–3 people",
    occasion: "朋友小聚 / 1v1请客",
    occasion_en: "Intimate friends dinner / 1-on-1 hosting",
    atmosphere: "板前吧台，安静专注",
    atmosphere_en: "Counter seating, quiet and focused",
    rating: 3,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H6eZ5FrwWLTUiAuN", label: "大众点评（世纪公园店）", label_en: "Dianping (Century Park)" },
      { url: "https://m.dianping.com/shopinfo/EfZkOREhKpnzycXo", label: "大众点评（前滩店）", label_en: "Dianping (Qiantan)" },
    ],
  },
  {
    name: "鲍师傅象山海鲜（板泉路店）",
    name_en: "Bào Shīfu Xiangshan Seafood (Banquan Rd)",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东 · 三林",
    neighborhood_en: "Pudong · Sanlin",
    address: "板泉路（三林地区）",
    address_en: "Banquan Road, Sanlin area, Pudong",
    description: "藏在三林街区的江浙小海鲜馆，食材新鲜，海鲜均按时令定价，价格实惠。其他海鲜也很新鲜，基本不踩雷。大厅环境正常但偏嘈杂，适合不在乎氛围的聚餐；包间有大有小（最小6人），适合谈事情或正式请客，可提前预定。",
    description_en: "A neighbourhood Jiangzhe seafood spot tucked in Sanlin, Pudong. Fresh produce, seasonal pricing on seafood, and good value overall. The rest of the menu is reliably fresh — hard to go wrong. The main hall is lively (read: noisy) — fine for casual gatherings. Private rooms range from 6-person to larger, great for business meals or hosting. Reservations available.",
    mustTry: ["家烧海鲜（精品杂鱼）", "竹蛏王", "炒海瓜子", "海鲜炒米粉（细粉·锅气足）", "丝瓜炒蛋"],
    mustTry_en: ["House-braised Mixed Seafood (家烧海鲜)", "King Razor Clams (竹蛏王)", "Stir-fried Cockles (炒海瓜子)", "Seafood Fried Rice Noodles — thin, great wok-breath (海鲜炒米粉)", "Loofah & Egg Stir-fry (丝瓜炒蛋)"],
    perPerson: "人均 ¥100–200（海鲜时令价）",
    perPerson_en: "~¥100–200 / person (seafood at market price)",
    reservation: "可预定，有大包间及6人小包间",
    reservation_en: "Reservations available; large and 6-person private rooms on offer",
    groupSize: "4–10+ 人",
    groupSize_en: "4–10+ people",
    occasion: "朋友聚餐 / 家庭聚餐 / 包间请客",
    occasion_en: "Friends dinner / Family meal / Private room hosting",
    atmosphere: "大厅嘈杂，包间安静",
    atmosphere_en: "Noisy main hall; quiet private rooms",
    rating: 2,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G81JLbccePjueIBf",
  },
  {
    name: "佬太公海鸭汤",
    name_en: "Lǎo Tài Gōng Sea Duck Soup",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "打浦桥 / 静安（两家均可）",
    neighborhood_en: "Dapuqiao / Jing'an (both branches)",
    address: "两家分店：上海总店（打浦桥）/ 静安店（南京西路商圈）",
    address_en: "Two branches: Main branch (Dapuqiao) / Jing'an branch (Nanjing West Rd area)",
    description: "以海鸭汤起家的江浙大排档，招牌是海鸭汤和油浸带鱼，其他海鲜也很新鲜，基本不踩雷。大厅环境正常但偏嘈杂，有大小包间可预约，适合不同规模聚餐。",
    description_en: "A Jiangzhe-style seafood canteen built around its signature sea duck soup and oil-poached hairtail. The rest of the seafood menu is reliably fresh — hard to go wrong. Main hall is lively and noisy; private rooms (small 6-person and large) available for quieter gatherings.",
    mustTry: ["油浸带鱼", "海鸭汤", "海肠捞饭", "油渣芋艿"],
    mustTry_en: ["Oil-poached Hairtail (油浸带鱼)", "Sea Duck Soup (海鸭汤)", "Sea Intestine Rice (海肠捞饭)", "Taro with Pork Crackling (油渣芋艿)"],
    perPerson: "人均 ¥100–200（海鲜时令价）",
    perPerson_en: "~¥100–200 / person (seafood at market price)",
    reservation: "可预定，有大包间及6人小包间",
    reservation_en: "Reservations available; large and 6-person private rooms on offer",
    groupSize: "4–10+ 人",
    groupSize_en: "4–10+ people",
    occasion: "朋友聚餐 / 家庭聚餐 / 包间请客",
    occasion_en: "Friends dinner / Family meal / Private room hosting",
    atmosphere: "大厅嘈杂，包间安静",
    atmosphere_en: "Noisy main hall; quiet private rooms",
    rating: 2,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H2Qc7kqTAylKpME3", label: "大众点评（上海总店）", label_en: "Dianping (Main Branch)" },
      { url: "https://m.dianping.com/shopinfo/G1G5xawoE0aa3nVB", label: "大众点评（静安店）", label_en: "Dianping (Jing'an)" },
    ],
  },
];
