const restaurants = [
  {
    name: "南蛮子（进贤路店）",
    name_en: "Nán Mán Zǐ (Jinxian Rd)",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "法租界 · 浦西核心区",
    neighborhood_en: "French Concession · Puxi",
    address: "徐汇·进贤路",
    address_en: "Jinxian Rd, Xuhui District",
    description: "火龙果心中第一名！2026年度回国的第一顿必须安排在这里！云南菜馆，藏在法租界的街边小店。环境正常偏简朴，明厨亮灶，隔着玻璃能直接看见后厨操作，锅气拉满。更适合朋友聚餐而非正式请客。没有包间，但楼上有大圆桌，2到10个人都能坐得舒服。",
    description_en: "火龙果's #1 in Shanghai — the first meal of every homecoming, no exceptions! A no-frills Yunnan spot in the French Concession. Lively open kitchen — you can watch the wok action through the glass. Better for friends than formal hosting. No private rooms, but upstairs has a big round table for 2–10.",
    mustTry: ["黑三剁", "木姜子牛肉", "菌子鸡汤", "炸排骨", "烤罗非鱼", "酥红豆", "辣子鸡", "牙签牛肉"],
    mustTry_en: ["Black Three-Mince (黑三剁)", "Litsea Beef (木姜子牛肉)", "Wild Mushroom Chicken Soup (菌子鸡汤)", "Fried Pork Ribs (炸排骨)", "Grilled Tilapia (烤罗非鱼)", "Crispy Red Beans (酥红豆)", "Chilli Chicken (辣子鸡)", "Toothpick Beef (牙签牛肉)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥100",
    perPerson_en: "~¥100 / person",
    reservation: "平时无需预定，周末饭点可在大众点评提前订位",
    reservation_en: "Walk-ins welcome on weekdays. For weekend peak hours, book ahead on Dianping.",
    groupSize: ["2–6人", "6人以上"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    emoji: "🌿",
    rating: 3,
    spicy: 1,
    dianping: "https://m.dianping.com/shop/2201962"
  },
  {
    name: "野果与山椒",
    name_en: "Yěguǒ & Shānjiāo",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "静安区 · 浦西",
    neighborhood_en: "Jing'an · Puxi",
    address: "静安·富民路 / 长寿路",
    address_en: "Two locations: Fumin Rd / Changshou Rd (both Jing'an District)",
    description: "贵阳老板开的正宗贵州菜，菜单设计很用心，经常按季节更新。强烈建议直接点菜吃，不要点酸汤火锅，菜比火锅好吃太多。这家的鸡尾酒调得也很好，有些独特小巧思！最好提前订位。没有包厢，环境热闹。更适合朋友聚餐，不适合请客吃饭。",
    description_en: "Authentic Guizhou cuisine by a Guiyang chef, with a thoughtfully designed menu that changes seasonally. Order à la carte — the dishes are far better than the sour-broth hotpot. The cocktails are surprisingly well-crafted with some creative twists. Book ahead. No private rooms, lively atmosphere. Better for friends than formal hosting.",
    mustTry: ["宫爆板筋", "铁签烤肉", "牛肉青菜锅", "辣子鸡", "脆哨土豆", "水豆豉茼蒿", "豆腐圆子", "洋芋粑"],
    mustTry_en: ["Kung Pao Tendon (宫爆板筋)", "Skewer Grilled Meat (铁签烤肉)", "Beef & Greens Pot (牛肉青菜锅)", "Chilli Chicken (辣子鸡)", "Crispy Lard Potato (脆哨土豆)", "Fermented Soybean Chrysanthemum (水豆豉茼蒿)", "Tofu Balls (豆腐圆子)", "Potato Cake (洋芋粑)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥120",
    perPerson_en: "~¥120 / person",
    reservation: "强烈建议提前在大众点评订位",
    reservation_en: "Reservations strongly recommended — book ahead on Dianping.",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "精致"],
    rating: 2,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/731796035", label: "大众点评（富民路店）", label_en: "Dianping (Fumin Rd)" },
      { url: "https://m.dianping.com/shop/1846224196", label: "大众点评（长寿路店）", label_en: "Dianping (Changshou Rd)" },
    ],
  },
  {
    name: "卿家姆",
    name_en: "Qīng Jiā Mǔ",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市多区·外滩店位置尤佳",
    address_en: "Locations across all districts; the Bund branch has the best location",
    description: "从宁波开来上海的江浙小海鲜馆子，精致而不做作。外滩店位置很好，但大厅无法订位，周末可能需要等位；包间可订但低消离谱，不建议。适合朋友聚餐或小规模请客，不适合家庭大桌。",
    description_en: "A Ningbo-origin Jiangzhe seafood restaurant, refined without being stuffy. The Bund branch has a great location — no reservations for the main hall (expect a wait on weekends), and private rooms have an unreasonable minimum spend. Best for friends or intimate hosting, not large family gatherings.",
    mustTry: ["熟醉大头虾", "小馆红烧肉", "爆炒黄牛肉", "腐竹黄鱼卷", "熟醉大闸蟹", "葱油东海小馆"],
    mustTry_en: ["Drunken Prawns (熟醉大头虾)", "Braised Pork — not sweet! (小馆红烧肉)", "Stir-fried Yellow Beef (爆炒黄牛肉)", "Tofu Skin & Yellow Croaker Roll (腐竹黄鱼卷)", "Drunken Hairy Crab (熟醉大闸蟹)", "Scallion Oil East Sea Catch (葱油东海小馆)"],
    priceRange: "¥¥¥",
    perPerson: "人均 ¥150–200",
    perPerson_en: "~¥150–200 / person",
    reservation: "大厅不可订位；包间可订但低消极高，不建议",
    reservation_en: "No reservations for main hall; private rooms available but minimum spend is excessive — not recommended.",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/1022572955", label: "大众点评（外滩店）", label_en: "Dianping (Bund)" },
      { url: "https://m.dianping.com/shop/877017586", label: "大众点评（中山公园店）", label_en: "Dianping (Zhongshan Park)" },
    ],
  },
  {
    name: "山石榴",
    name_en: "Shān Shí Liú",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市多区",
    address_en: "Multiple locations citywide",
    description: "全上海最标准化的贵州菜，出品稳定不踩雷，包含所有经典菜色，适合一站式体验正宗贵州菜。花溪牛肉粉超适合一人食，中午去吃一碗美滋滋。个人认为酸汤鱼做得一般，但很受大众欢迎。不能订座，只能现场排队，建议早去或错峰；可外卖，味道和堂食基本一致。无包厢，环境偏热闹。更适合朋友聚餐，不适合请客吃饭。",
    description_en: "The most consistent Guizhou chain in Shanghai — reliable across the board, covers all the classics. Great for a one-stop intro to Guizhou cuisine. The Huaxi beef noodles are a perfect solo lunch. The sour fish soup is popular but unremarkable in 火龙果's view. No reservations — queue in person, go early or off-peak. Delivery holds up well. No private rooms, lively vibe. Better for friends than formal hosting.",
    mustTry: ["宫爆板筋", "雷家豆腐圆子", "辣子鸡", "糟辣小炒肉", "铁签烤肉", "水豆豉炒蓬蒿菜", "花溪牛肉粉（一人食首选）"],
    mustTry_en: ["Kung Pao Tendon (宫爆板筋)", "Leijia Tofu Balls (雷家豆腐圆子)", "Chilli Chicken (辣子鸡)", "Pickled Chilli Stir-fry (糟辣小炒肉)", "Skewer Grilled Meat (铁签烤肉)", "Fermented Soybean Chrysanthemum (水豆豉炒蓬蒿菜)", "Huaxi Beef Noodles — perfect solo (花溪牛肉粉)"],
    priceRange: "¥¥",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["一人食", "朋友聚餐"],
    atmosphere: ["热闹", "精致"],
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    rating: 1,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G9WTLikdO9Rtriua", label: "大众点评（K11店）", label_en: "Dianping (K11 Mall)" },
      { url: "https://m.dianping.com/shopinfo/H3tsUJ3AA6GA6mo8", label: "大众点评（西岸梦中心店）", label_en: "Dianping (West Bund Dream Centre)" },
    ],
  },
  {
    name: "清晨落夜小酒馆",
    name_en: "Qīngchén Luòyè Xiǎojiǔguǎn",
    category: "jiangxi",
    category_en: "jiangxi",
    neighborhood: "静安寺 · 静安区",
    neighborhood_en: "Jing'an Temple · Jing'an District",
    address: "静安·静安寺",
    address_en: "Near Jing'an Temple, Jing'an District",
    description: "江西菜小酒馆，江西人认证正宗。辣得很，爆炒的菜都挺好吃。",
    description_en: "Jiangxi cuisine wine bar, certified authentic by actual Jiangxi locals. Seriously spicy — the stir-fried dishes are the highlights.",
    mustTry: ["爆炒系列菜"],
    mustTry_en: ["Stir-fried dishes (爆炒系列)"],
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹"],
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    rating: 2,
    spicy: 5,
    dianping: "https://m.dianping.com/shop/1804042946",
  },
  {
    name: "炙苑",
    name_en: "Zhì Yuàn",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "浦东 · 世纪公园板块",
    neighborhood_en: "Pudong · Century Park",
    address: "浦东·世纪公园",
    address_en: "Kerry Parkside, Pudong New Area",
    description: "日式烧肉天花板，没有并列的。什么肉都好吃，可以根据人数和喜好点拼盘，反正点下来都差不多贵。碾压铁屋、老干杯、橘炎胡同等一众高端日式烧肉。人均500不含酒已经能吃得非常满足。",
    description_en: "The undisputed peak of Japanese yakiniku in Shanghai — nothing comes close. Every cut is exceptional; order a combo platter sized to your group. Leaves Iron House, Don Quijote, and every other high-end yakiniku in the dust. ¥500/person ex-drinks is more than satisfying.",
    mustTry: ["拼盘（按人数点）", "和牛海胆塔塔", "海胆和牛釜饭"],
    mustTry_en: ["Combo Platter (sized to group)", "Wagyu & Uni Tartare (和牛海胆塔塔)", "Uni Wagyu Kamameshi (海胆和牛釜饭)"],
    priceRange: "¥¥¥¥",
    perPerson: "人均 ¥500（不点酒）",
    perPerson_en: "~¥500 / person (ex-drinks)",
    reservation: "可提前订位，有包间",
    reservation_en: "Reservations available; private rooms offered.",
    groupSize: ["2–6人", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 3,
    dianping: "https://www.dianping.com/shop/H3pRXBQ0J4tT09I2",
  },
  {
    name: "鮨小野",
    name_en: "Sushi Ono",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "世纪公园 / 前滩（两家均可）",
    neighborhood_en: "Century Park / Qiantan (both branches)",
    address: "浦东·世纪公园 / 前滩",
    address_en: "Two branches: Century Park / Qiantan",
    description: "板前寿司，可以自己点单——千万不要点套餐，直接点你想吃的，每一样都极度新鲜！火龙果力推：比很多人均1k+的日料还新鲜还好吃，性价比和味道全部拉满。因为只有板前，人多了坐一排会根本听不到彼此说话，2-3人最适合。必须提前大众点评预约，座位有限！",
    description_en: "Omakase-counter sushi where you order à la carte — skip the set menu and just pick what you want, everything is supremely fresh! 火龙果's top pick: beats many ¥1000+/head places on both quality and value. Counter-only seating means groups of 4+ can't really talk to each other — keep it to 2–3. Dianping reservation required, seats are limited!",
    mustTry: ["各类海胆", "枪鱿鱼", "金枪鱼", "枪鱿鱼海胆寿司（火龙果挚爱）"],
    mustTry_en: ["Sea Urchin (all kinds)", "Squid (枪鱿鱼)", "Tuna (金枪鱼)", "Squid & Uni Sushi — 火龙果's #1 pick"],
    perPerson: "人均 ¥500–800（不含酒）",
    perPerson_en: "~¥500–800 / person (excl. drinks)",
    reservation: "必须提前大众点评预约，座位非常有限",
    reservation_en: "Dianping reservation required — very limited seats",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["安静"],
    rating: 3,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H6eZ5FrwWLTUiAuN", label: "大众点评（世纪公园店）", label_en: "Dianping (Century Park)" },
      { url: "https://m.dianping.com/shopinfo/EfZkOREhKpnzycXo", label: "大众点评（前滩店）", label_en: "Dianping (Qiantan)" },
    ],
  },
  {
    name: "鲍师傅象山海鲜（板泉路店）",
    name_en: "Bào Shīfu Xiangshan Seafood (Banquan Rd)",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东 · 三林",
    neighborhood_en: "Pudong · Sanlin",
    address: "浦东·三林",
    address_en: "Banquan Road, Sanlin area, Pudong",
    description: "藏在三林街区的江浙小海鲜馆，食材新鲜，海鲜均按时令定价，价格实惠。其他海鲜也很新鲜，基本不踩雷。大厅环境正常但偏嘈杂，适合不在乎氛围的聚餐；包间有大有小（最小6人），适合谈事情或正式请客，可提前预定。",
    description_en: "A neighbourhood Jiangzhe seafood spot tucked in Sanlin, Pudong. Fresh produce, seasonal pricing on seafood, and good value overall. The rest of the menu is reliably fresh — hard to go wrong. The main hall is lively (read: noisy) — fine for casual gatherings. Private rooms range from 6-person to larger, great for business meals or hosting. Reservations available.",
    mustTry: ["家烧海鲜（精品杂鱼）", "竹蛏王", "炒海瓜子", "海鲜炒米粉（细粉·锅气足）", "丝瓜炒蛋"],
    mustTry_en: ["House-braised Mixed Seafood (家烧海鲜)", "King Razor Clams (竹蛏王)", "Stir-fried Cockles (炒海瓜子)", "Seafood Fried Rice Noodles — thin, great wok-breath (海鲜炒米粉)", "Loofah & Egg Stir-fry (丝瓜炒蛋)"],
    perPerson: "人均 ¥100–200（海鲜时令价）",
    perPerson_en: "~¥100–200 / person (seafood at market price)",
    reservation: "可预定，有大包间及6人小包间",
    reservation_en: "Reservations available; large and 6-person private rooms on offer",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "家庭聚餐", "可以请客"],
    atmosphere: ["热闹"],
    rating: 2,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G81JLbccePjueIBf",
  },
  {
    name: "佬太公海鸭汤",
    name_en: "Lǎo Tài Gōng Sea Duck Soup",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "打浦桥 / 静安（两家均可）",
    neighborhood_en: "Dapuqiao / Jing'an (both branches)",
    address: "黄浦·打浦桥 / 静安·南京西路",
    address_en: "Two branches: Main branch (Dapuqiao) / Jing'an branch (Nanjing West Rd area)",
    description: "以海鸭汤起家的江浙大排档，招牌是海鸭汤和油浸带鱼，其他海鲜也很新鲜，基本不踩雷。大厅环境正常但偏嘈杂，有大小包间可预约，适合不同规模聚餐。",
    description_en: "A Jiangzhe-style seafood canteen built around its signature sea duck soup and oil-poached hairtail. The rest of the seafood menu is reliably fresh — hard to go wrong. Main hall is lively and noisy; private rooms (small 6-person and large) available for quieter gatherings.",
    mustTry: ["油浸带鱼", "海鸭汤", "海肠捞饭", "油渣芋艿"],
    mustTry_en: ["Oil-poached Hairtail (油浸带鱼)", "Sea Duck Soup (海鸭汤)", "Sea Intestine Rice (海肠捞饭)", "Taro with Pork Crackling (油渣芋艿)"],
    perPerson: "人均 ¥100–200（海鲜时令价）",
    perPerson_en: "~¥100–200 / person (seafood at market price)",
    reservation: "可预定，有大包间及6人小包间",
    reservation_en: "Reservations available; large and 6-person private rooms on offer",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "家庭聚餐", "可以请客"],
    atmosphere: ["热闹"],
    rating: 2,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H2Qc7kqTAylKpME3", label: "大众点评（上海总店）", label_en: "Dianping (Main Branch)" },
      { url: "https://m.dianping.com/shopinfo/G1G5xawoE0aa3nVB", label: "大众点评（静安店）", label_en: "Dianping (Jing'an)" },
    ],
  },
  {
    name: "家康居酒屋",
    name_en: "Jiakang Izakaya",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "全市多家分店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市多区",
    address_en: "Multiple locations citywide",
    description: "平价日式居酒屋，招牌蘸面是来了必点的东西——面条极度劲道，蘸汁浓郁醇厚，满足感拉满。座位偏小，氛围热闹，没有包间。一个人来饱腹一顿或者朋友小聚都很合适，不适合请客或家庭聚餐。千万千万千万记得提前大众点评预约，不约大概率吃不上！",
    description_en: "A budget-friendly izakaya, best known for its tsukemen (dipping ramen) — springy noodles with a rich, deeply flavoured broth. Small seats, lively vibe, no private rooms. Perfect solo or for a casual friends hangout; not for hosting or family dinners. MUST reserve on Dianping in advance — walk-ins almost never get in!",
    mustTry: ["蘸面（面劲道，汤汁浓郁）"],
    mustTry_en: ["Tsukemen / Dipping Ramen — springy noodles, rich broth (蘸面)"],
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    reservation: "必须提前大众点评预约，不约大概率没位",
    reservation_en: "Dianping reservation essential — walk-ins almost always turned away",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["一人食", "朋友聚餐"],
    atmosphere: ["热闹"],
    rating: 1,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G2xiNKXTFw23ZOta",
  },
  {
    name: "贰粉之壹·宁波海鲜米粉",
    name_en: "Èr Fěn Zhī Yī · Ningbo Seafood Rice Noodles",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "徐汇·交通大学",
    neighborhood_en: "Xuhui · Jiaotong University",
    address: "徐汇·交通大学",
    address_en: "Near Zhongshan Park, Changning District",
    description: "宁波风味海鲜米粉小馆，火龙果强烈推荐炒粉——烤虾炒粉用的是细粉，锅气非常足，香！汤粉也很鲜美，不过炒粉才是灵魂。就是小面馆的环境，简单实惠，一个人来饱腹一顿最合适，价格非常亲民，还可以外卖。",
    description_en: "A Ningbo-style seafood rice noodle shop. 火龙果 strongly recommends the stir-fried version — grilled prawn fried noodles with thin rice noodles and serious wok breath. The soup noodles are also fresh and tasty, but the fried is the star. Simple canteen vibes, great value, delivery available too.",
    mustTry: ["烤虾炒粉（细粉·锅气十足）"],
    mustTry_en: ["Grilled Prawn Fried Rice Noodles — thin noodles, incredible wok breath (烤虾炒粉)"],
    perPerson: "人均 ¥30–50，可外卖",
    perPerson_en: "~¥30–50 / person · delivery available",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["一人食", "朋友聚餐"],
    atmosphere: ["简单"],
    rating: 1,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/H5uK2LHMnmh9Dt0k?msource=Appshare2021&utm_source=shop_share&shoptype=10&shopcategoryid=210&cityid=1&isoversea=0",
  },
  {
    name: "甬府尊鲜",
    name_en: "Yǒng Fǔ Zūn Xiān",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "陆家嘴 / 前滩（两家均可）",
    neighborhood_en: "Lujiazui / Qiantan (both branches)",
    address: "浦东·陆家嘴 / 前滩",
    address_en: "Two branches: IFC Mall (Lujiazui) / Qiantan Taikoo Li",
    description: "注意是甬府「尊鲜」，不是小鲜。高端浙菜馆，环境精致，适合请客。火龙果每次都专程来吃花雕鸡和沙蒜豆面——这两道必点，其他海鲜价格偏贵且不算特别出彩，可选择性点。可订位，有包间。",
    description_en: "Note: this is 尊鲜 (Zūn Xiān), not 小鲜. An upscale Zhejiang restaurant, great for hosting. 火龙果comes specifically for the Shaoxing wine chicken and sand garlic bean noodles — these two are unmissable. The rest of the seafood menu is pricey and unremarkable by comparison, order selectively. Reservations and private rooms available.",
    mustTry: ["花雕鸡（软烂入味）", "沙蒜豆面（鲜糯入味）"],
    mustTry_en: ["Shaoxing Wine Chicken — tender, deeply flavoured (花雕鸡)", "Sand Garlic Bean Noodles — fresh, sticky, full of flavour (沙蒜豆面)"],
    perPerson: "人均 ¥200–300（海鲜时令价）",
    perPerson_en: "~¥200–300 / person (seafood at market price)",
    reservation: "可订位，有包间",
    reservation_en: "Reservations available; private rooms on offer",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["可以请客"],
    atmosphere: ["精致"],
    rating: 1,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G3HVGusYW92ygHcK", label: "大众点评（国金中心店）", label_en: "Dianping (IFC Mall)" },
      { url: "https://m.dianping.com/shopinfo/jBvgUk3qXeiBdt7w", label: "大众点评（前滩太古里店）", label_en: "Dianping (Qiantan Taikoo Li)" },
    ],
  },
  {
    name: "台州老六海鲜面馆",
    name_en: "Taizhou Lao Liu Seafood Noodles",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东·三林 / 世纪大道",
    neighborhood_en: "Pudong · Sanlin / Century Ave",
    address: "浦东·三林 / 世纪大道",
    address_en: "Pudong · Sanlin / Century Ave",
    description: "台州家烧风味的海鲜面馆，招牌小网海鲜面里有一整只梭子蟹和一整条小黄鱼，加上蛏子、花甲、虾、年糕、青菜，鲜掉眉毛！人多可点至尊海鲜拼盘，应有尽有。小面馆环境，价格非常亲民。⚠️ 强烈不建议外卖，外卖分量比堂食少很多，而且海鲜放一会儿口感大打折扣，一定要堂食！",
    description_en: "Taizhou-style braised seafood noodle shop. The signature 'small net' seafood noodles come loaded — a whole swimming crab, a whole yellow croaker, razor clams, cockles, prawns, rice cakes and greens. Insanely fresh. For groups, the deluxe seafood platter has everything. Great value, casual setting. ⚠️ Strongly avoid delivery — portions are smaller and seafood loses its magic fast. Dine in only!",
    mustTry: ["招牌小网海鲜面（一整只梭子蟹+黄鱼）", "海鲜炒年糕", "大黄鱼海鲜面", "至尊海鲜拼盘（人多时）"],
    mustTry_en: ["Signature Seafood Noodles — whole crab + yellow croaker (招牌小网海鲜面)", "Seafood Fried Rice Cakes (海鲜炒年糕)", "Yellow Croaker Seafood Noodles (大黄鱼海鲜面)", "Deluxe Seafood Platter for groups (至尊海鲜拼盘)"],
    perPerson: "人均 ¥50",
    perPerson_en: "~¥50 / person",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["一人食", "朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 2,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H3ZesXqC88tD6rQ4", label: "大众点评（上南总店）", label_en: "Dianping (Shangnan Main Branch)" },
      { url: "https://m.dianping.com/shopinfo/k86yv3h71DRoLyph", label: "大众点评（世纪汇店）", label_en: "Dianping (Century Link)" },
    ],
  },
  {
    name: "台乡缘（世博中心店）",
    name_en: "Táixiāngyuán (World Expo branch)",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东·世博园",
    neighborhood_en: "Pudong · World Expo",
    address: "浦东·世博园",
    address_en: "Pudong · World Expo Park",
    description: "认准世博中心店，其他店不行。台州菜代表，海鲜新鲜，家烧风味最大程度展示食材本味。环境高雅，非常适合请客，也适合朋友聚餐。6人以上可以订包间，有低消但不离谱（也可以据理力争，火龙果干成功过）。相对于台州菜天花板新荣记，性价比更高。需要销售联系方式可以找火龙果本人。避雷菜：墨鱼肠鱼饼。",
    description_en: "World Expo branch only — the other locations don't compare. The benchmark for Taizhou cuisine in Shanghai. Impeccably fresh seafood, home-style braising that lets the ingredients shine. Elegant setting, perfect for hosting. Private rooms for 6+ with a reasonable minimum spend (negotiable — 火龙果 has successfully talked them down). Better value than the revered Xin Rong Ji. Contact 火龙果 directly for the sales rep. Avoid: squid intestine fish cake (墨鱼肠鱼饼).",
    mustTry: ["各类家烧海鲜", "石锅芋艿（软糯入味！）", "沙蒜豆面", "盐卤手撕豆腐"],
    mustTry_en: ["House-braised Seasonal Seafood", "Stone Pot Taro — impossibly silky (石锅芋艿)", "Sand Garlic Bean Noodles (沙蒜豆面)", "Salt-brined Hand-torn Tofu (盐卤手撕豆腐)"],
    perPerson: "人均 ¥200–300（海鲜时令价）",
    perPerson_en: "~¥200–300 / person (seafood at market price)",
    reservation: "可订位，6人以上可订包间（有低消）",
    reservation_en: "Reservations available; private rooms for 6+ with minimum spend",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 2,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G3ytXFWEuiVIwkRh",
  },
  {
    name: "老兴鲜（黄浦店）",
    name_en: "Lǎo Xīng Xiān (Huangpu)",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "黄浦·淮海路",
    neighborhood_en: "Huangpu · Huaihai Rd",
    address: "黄浦·淮海路",
    address_en: "Huaihai Rd, Huangpu District",
    description: "火龙果唯一推荐的上海本帮菜！黑珍珠认证，本帮菜与江浙小海鲜双线出品，食材极度新鲜，出品极其稳定，名不虚传。必须提前预订。",
    description_en: "火龙果's one and only recommended Shanghai cuisine restaurant — Black Pearl certified. Covers both 本帮菜 and Jiangzhe seafood with exceptional consistency. Ingredients are impeccably fresh. Advance reservation required.",
    mustTry: ["白烧鳝背", "老兴鲜全家福", "鲜虾春卷", "清炒河虾仁", "酒香草头"],
    mustTry_en: ["White-braised Eel Back (白烧鳝背)", "Lao Xing Xian Seafood Platter (老兴鲜全家福)", "Fresh Prawn Spring Rolls (鲜虾春卷)", "Stir-fried River Shrimp (清炒河虾仁)", "Wine-fragrant Clover (酒香草头)"],
    perPerson: "人均 ¥250–350",
    perPerson_en: "~¥250–350 / person",
    reservation: "必须提前预订",
    reservation_en: "Advance reservation required",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "安静"],
    rating: 2,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/H7vprrMRBaF2iOCZ",
  },
  {
    name: "美醉煨汤",
    category: "jiangzhe",
    address: "黄浦·大沽路",
    description: "环境很舒服的小店，基本都是江浙经典海鲜烧法，食材新鲜且出品稳定，可以放心点菜，但说不上特别惊艳，推荐的点主要在菜水平不错+氛围很好，很适合几个姐妹吃吃饭聊聊天，还有个小院子，春夏之交坐在院子里非常舒适。",
    mustTry: ["墨鱼排骨汤", "家烧台州红虾", "家烧蛏子"],
    perPerson: "人均 ¥200–300（海鲜时令价）",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/HaDjlf30WUZ4zxJj",
  },
  {
    name: "威皇广福和小海鲜",
    category: "jiangzhe",
    address: "全市多家分店",
    description: "花雕醉鸡煲的鲜美这么多年都出品稳定，是冬天隔段时间就会想喝的！推荐顺序：先喝鸡汤，再下海鲜，最后下牛肉！不可预定，饭点排队，建议错峰前往。",
    mustTry: ["花雕醉鸡煲", "煲仔饭"],
    perPerson: "人均 ¥100",
    reservation: "不可预定，饭点排队，建议错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "简单"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l1HFMJvA6u6HXcya", label: "大众点评（襄阳南路店）" },
      { url: "https://m.dianping.com/shopinfo/l9dBzhcgS9NHAckz", label: "大众点评（乌鲁木齐南路店）" },
      { url: "https://m.dianping.com/shopinfo/laLQpd0xqQP9ZgCQ", label: "大众点评（嘉善路店）" },
    ],
  },
  {
    name: "旧村·砂锅焗海鲜",
    category: "jiangzhe",
    address: "全市多家分店",
    description: "世界上最好吃的鸦片鱼头！黄油的香气和鸦片鱼头的鲜味被砂锅完美地融合并包裹，火龙果一人每次可吃掉一大份！皮皮虾和梭子蟹季节推荐干焗，虾肉和蟹肉的鲜美都透着黄油奶香味。猪蹄鸡爪炖得非常软烂，入口即化。唯一缺点：吃多了有点咸，口淡的朋友慎入。不可预定，饭点排队，建议错峰前往。",
    mustTry: ["鸦片鱼头", "干焗皮皮虾", "干焗梭子蟹", "猪蹄鸡爪煲"],
    perPerson: "人均 ¥100–150（海鲜时令价）",
    reservation: "不可预定，饭点排队，建议错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "简单"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l4RK3z1HcJzRuL0G", label: "大众点评（世纪汇店）" },
      { url: "https://m.dianping.com/shopinfo/l7x4O7o1ocBfSPLn", label: "大众点评（合生汇店）" },
    ],
  },
  {
    name: "地球美食剧场",
    category: "japanese",
    address: "长宁·番禺路",
    description: "仪式感拉满的纪念日/生日推荐，食材根据季节变化，新鲜度和出品都令人安心。大屏幕随季节和食材变化，从日出后的潺潺流水到夜幕后的璀璨烟花，视觉和味觉都很享受的两个小时。最后会一起动手做可爱的小纪念品（比如一小瓶柚子酒），大屏幕上还有庆祝画面。花下去的钱从各方面来说都得到了满意的体验。",
    mustTry: ["随季节时令套餐"],
    perPerson: "人均 ¥1000",
    reservation: "提前预定",
    groupSize: ["2–6人"],
    occasion: ["可以请客"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/k8ZlQIWaZmVOAxSP",
  },
  {
    name: "ATELIER IZAKAYA",
    category: "japanese",
    address: "全市两家分店",
    description: "好吃的漂亮饭，环境属于经典精致bistro，烧鸟味道都不错，下酒菜偏多，适合生日或者三五好友聚聚。都是长桌子，人多了会有坐得太散听不到讲话的问题。烧鸟都是单点，丰俭由人。要预定。",
    mustTry: ["紫苏鸡腿肉", "牛肋条", "鸡肉丸子"],
    perPerson: "人均 ¥250–500",
    reservation: "要预定",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "精致"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G58m51Vc4ikIL0Lv", label: "大众点评（外滩店）" },
      { url: "https://m.dianping.com/shopinfo/H2NnweVAEb4mQOZP", label: "大众点评（南京西路店）" },
    ],
  },
  {
    name: "佬表炒菜猛",
    category: "jiangxi",
    address: "浦东·蓝村路",
    description: "南昌人推荐唯一南昌爆炒店，锅气正确，无须其他语言赘述！大厅适合2-4人，有大包间。平常不太排队，但饭点可以预定一下比较保险，可以点外卖，美味不减。",
    mustTry: ["辣炒鲜吊龙", "干锅有机芦笋干（贡菜干）", "火爆片片毛肚", "辣鸡爪", "招牌热辣小炒鸡", "绝杀莲花血鸭"],
    perPerson: "人均 ¥100",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "简单"],
    rating: 3,
    spicy: 5,
    dianping: "https://m.dianping.com/shopinfo/G6d756SR6pbjVvZH",
  },
  {
    name: "望庐·江西荟馆",
    category: "jiangxi",
    address: "浦东·前滩",
    description: "环境精致且味道正宗的江西菜，非常适合请客，尤其是作为江西人带大家吃吃江西菜，很好的体验。萍乡血鸭做的非常正宗，馋的时候自己一个人去吃一份也很满足，从头辣到脚！",
    mustTry: ["辣椒炒肉", "辣藕", "萍乡血鸭", "年糕炒白蟹"],
    perPerson: "人均 ¥280",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["安静", "精致"],
    rating: 1,
    spicy: 5,
    dianping: "https://m.dianping.com/shopinfo/HaHXztxyYYijLwSg",
  },
];
